networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: ssap018/mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
  user:
    image: ssap018/user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  catalogue:
    image: ssap018/catalogue:v1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb    
  cart:
    image: ssap018/cart:v1
    container_name: cart
    networks:
    - roboshop
    depends_on:
    - redis
    - catalogue
  mysql:
    image: ssap018/mysql:v1
    container_name: mysql
    networks:
      - roboshop
  shipping:
    image: ssap018/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql    
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
  payment:
    image: ssap018/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
  web:
    image: ssap018/web:v1
    container_name: web
    networks:
      - roboshop
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
  